### PR TITLE
Use safe getter for fallback_name

### PR DESCRIPTION
**Pull request by withinfocus**
Use a safe getter for `fallback_name` instead of a direct array reference. The fallback name may be `None` in some cases and will be handled later by callers.

### CODE REVIEW

**Comment by AllenBurgett** [comment]
@withinfocus, it looks good to me. I tested it on my data set and received an xml file of the same size as the master branch provided. I also tested the -p flag and noticed that it doesn't seem to map the user's selection. I'm wondering if we want a reference dict per Google user ID. I was prompted multiple times to enter a phone number for the same Google ID. Just curious if that's the desired result.

**Comment by withinfocus** [comment]
Awesome that it's working. Yeah, I didn't make this fancy enough to utilize any sort of map for reuse. I wouldn't say that's desired but it does seem like a good enhancement to build on this.

**Comment by AllenBurgett** [comment]
Cool. So, do we want to target that functionality before the merge or for future work?

**Comment by withinfocus** [comment]
I would say that's best as future work. This works as-is and can be built upon.

**Comment by withinfocus** [comment]
This good to merge then?

**Comment by AllenBurgett** [comment]
Yep. Sorry for the delay.

**Comment by withinfocus** [comment]
Good stuff, thanks! I'll see about some additional enhancements like that map.

**Pull request merged**
